build:
  environment:
    php: 7.2.13
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

    coverage:
      tests:
        override:
          - command: php vendor/bin/phpunit
            coverage:
              file: build/logs/clover.xml
              format: clover

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: ["src/*"]