language: php

php:
    - "7.2"
    - nightly

matrix:
  allow_failures:
    - php: nightly

install:
    - composer install

before_script:
  - composer validate --strict

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
 
