<?php
/**
 * Created by PhpStorm.
 * User: famoser
 * Date: 05/09/2017
 * Time: 08:54
 */

namespace Famoser\XKCDCache\Tests\ControllerTests\Base;


use Famoser\XKCDCache\Tests\Utils\TestHelper\TestHelper;
use PHPUnit\Framework\TestCase;

abstract class BaseTestController extends TestCase
{
    /* @var TestHelper $testHelper */
    private $testHelper;

    /**
     * FrontendTestController constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->testHelper = $this->constructTestHelper();
    }

    /**
     * return the test helper you want to use
     *
     * @return TestHelper
     */
    abstract protected function constructTestHelper();

    /**
     * returns the TestHelper constructed with constructTestHelper
     * @return mixed
     */
    protected function getTestHelper()
    {
        return $this->testHelper;
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->testHelper->cleanEnvironment();
    }
}